version: "1.0.0"

server:
  http:
    host: localhost
    port: 9000

kafka:
  kafkaUrl: localhost:29092
  batchSize: 1
  batchTimeout: 100

endpoints:
  - path: /pavle
    method: POST
    dataType: json
    passthrough: true
    kafka:
      topic: my-topic